version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: harambot
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: harambot_db

  harambot:
    image: harambot:latest
    restart: always
    depends_on:
      - db
    environment:
      DISCORD_TOKEN: 
      YAHOO_KEY:
      YAHOO_SECRET: 
      DATABASE_URL:
      # GUILD_ID: 
      # CHANNEL_ID: 
