services:
- type: web
  name: harambot-service
  runtime: image
  image:
      url: docker.io/jayde250/harambot:latest
  plan: free
  envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: YAHOO_KEY
        sync: false
      - key: YAHOO_SECRET
        sync: false
      - key: GUILD_ID
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: DATABASE_URL
        fromDatabase:
            name: harambot-database
            property: connectionString
      - key: VERSION
        value: "0.3.2-Beta"

databases:
- name: harambot-database
  databaseName: harambot
  user: harambot
  plan: free
